In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('train.txt' , sep = ';' , header = None , names = ['text' , 'emotion'])

In [3]:
df

                                                    text  emotion
0                                i didnt feel humiliated  sadness
1      i can go from feeling so hopeless to so damned...  sadness
2       im grabbing a minute to post i feel greedy wrong    anger
3      i am ever feeling nostalgic about the fireplac...     love
4                                   i am feeling grouchy    anger
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...  sadness
15996  i am now turning and i feel pathetic that i am...  sadness
15997                     i feel strong and good overall      joy
15998  i feel like this was such a rude comment and i...    anger
15999  i know a lot but i feel so stupid because i ca...  sadness

[16000 rows x 2 columns]

In [4]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [5]:
emotions = df['emotion'].unique()
emotions_numeric = {}
i = 0
for emo in emotions :
    emotions_numeric[emo] = i
    i += 1
df['emotion'] = df['emotion'].map(emotions_numeric)

In [6]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [7]:
df['text'] = df['text'].apply(lambda x : x.lower())

In [8]:
import string

In [9]:
def remove_punc(txt):
    return txt.translate(str.maketrans('' , '' , string.punctuation))

In [10]:
df['text'] = df['text'].apply(remove_punc)

In [11]:
def remove_num(txt):
    new = ""
    for i in txt :
        if not i.isdigit():
            new = new + i
    return new

df['text'] = df['text'].apply(remove_num)

In [12]:
def remove_emoji(txt):
    new = ""
    for i in txt :
        if not i.isascii():
            new = new + i
    return new

df['text'] = df['text'].apply(remove_num)

In [13]:
import nltk # to remove stopping words like is , am , the

In [14]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [15]:
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\LENOVO\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\LENOVO\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [16]:
stop_words = set(stopwords.words('english'))

In [17]:
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [18]:
len(stop_words)

198

In [19]:
def remove_stop(txt):
    words = word_tokenize(txt)
    cleaned_text = []
    for i in words:
        if not i in stop_words:
            cleaned_text.append(i)
    return ' '.join(cleaned_text)

In [20]:
df['text'] = df['text'].apply(remove_stop)

In [21]:
df

                                                    text  emotion
0                                  didnt feel humiliated        0
1      go feeling hopeless damned hopeful around some...        0
2              im grabbing minute post feel greedy wrong        1
3      ever feeling nostalgic fireplace know still pr...        2
4                                        feeling grouchy        1
...                                                  ...      ...
15995      brief time beanbag said anna feel like beaten        0
15996  turning feel pathetic still waiting tables sub...        0
15997                           feel strong good overall        5
15998                     feel like rude comment im glad        1
15999                       know lot feel stupid portray        0

[16000 rows x 2 columns]

In [22]:
X = df['text']
y = df['emotion']

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.30 , random_state = 42)

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer , CountVectorizer

### Using Bag of Words Vectorizer with Naive Bias

In [26]:
bow_vectorizer = CountVectorizer()

In [27]:
X_train_bow = bow_vectorizer.fit_transform(X_train)

In [28]:
X_test_bow = bow_vectorizer.transform(X_test)

In [29]:
from sklearn.naive_bayes import MultinomialNB

In [30]:
model_nb = MultinomialNB()

In [31]:
model_nb.fit(X_train_bow , y_train)

MultinomialNB()

In [32]:
y_pred = model_nb.predict(X_test_bow)

In [33]:
from sklearn.metrics import accuracy_score

In [34]:
accuracy_score(y_test , y_pred)

0.7672916666666667

### Using TF-ID Vectorizer with Naive Bias

In [35]:
tf_vectorizer = TfidfVectorizer()

In [36]:
X_train_tf = tf_vectorizer.fit_transform(X_train)

In [37]:
X_test_tf = tf_vectorizer.transform(X_test)

In [38]:
model_nb2 = MultinomialNB()

In [39]:
model_nb2.fit(X_train_tf , y_train)

MultinomialNB()

In [40]:
y_pred_tf = model_nb2.predict(X_test_tf)

In [41]:
accuracy_score(y_test , y_pred_tf)

0.6622916666666666

### Using TF-ID Vectorizer with Logistic Regression

In [42]:
from sklearn.linear_model import LogisticRegression

In [43]:
model_LR = LogisticRegression()

In [44]:
model_LR.fit(X_train_tf , y_train)

LogisticRegression()

In [45]:
y_pred = model_LR.predict(X_test_tf)

In [46]:
accuracy_score(y_pred , y_test) #heighest accuracy

0.8516666666666667

In [47]:
import joblib

In [48]:
import joblib

# Save the TF-IDF vectorizer
joblib.dump(tf_vectorizer, "NLP_Emotions_vectorizer.joblib")

# Save the trained Logistic Regression model
joblib.dump(model_LR, "NLP_Emotions_model.joblib")

print("Model and vectorizer saved successfully!")
print("Number of TF-IDF features:", len(tf_vectorizer.vocabulary_))

Model and vectorizer saved successfully!
Number of TF-IDF features: 12452